steps:
  # Pull the latest image for layer caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:latest || true

  # Build with cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:${SHORT_SHA}',
      '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:latest',
      '--cache-from', 'us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:latest',
      '.'
    ]

  # Push both tagged image and 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'hypetrade'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/hypetrade-repo/hypetrade-app:${SHORT_SHA}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1

# what

timeout: 1800s