version: "3.9"
services:
  frontend:
    build:
      context: ./HypeTrade307
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./HypeTrade307:/app
      - /HypeTrade307/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./src
    ports:
      - "8080:8080"
    volumes:
      - .
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: rootpass
#    ports:
#      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: